### ISSUE TITLE
Could log output be shown in tests?

### ISSUE THREAD

**Issue by martinlindhe** [rust-lang-nursery/log#106]
Normally running tests mutes standard output, but using this rather obscure command `cargo test -- --nocapture`, output such as `println!("something");` is shown in the test result.
This is  great for debugging. However, it doesn't appear to work with the log macros.

I found #56 which documents how to enable output in tests specifically, but I am wondering if there is some easier way?

**Comment by sfackler** [comment]
This seems like more of a rust-lang/rust issue than this crate - `log` doesn't touch `println` at all.

**Comment by martinlindhe** [comment]
@sfackler Thanks for clarifying! I think I got confused by the [documentation](https://github.com/rust-lang-nursery/log/blob/aa137f5b9e69c2ad38a1aedfafa84addeb14077c/src/lib.rs#L112).

**Comment by martinlindhe** [comment]
Posting for reference: After some digging, I found a report of this already at https://github.com/rust-lang/rust/issues/40298

**Comment by cbarber** [comment]
Leaving this for google results. A decent work around:
```
#[cfg(not(test))]
use log::{info, warn};
 
#[cfg(test)]
use std::{println as info, println as warn};
```

**Comment by AlejandroFNadal** [comment]
Add in each test, instead of
`#[test]`
put:

`#[test_log::test]`

Then, to cargo toml
```
[dev-dependencies]
test-log = "*"
```

Finally, set env variable to desired debugging level:
`export RUST_LOG="debug"`
