### ISSUE TITLE
Very long build times (~3-4 minutes) for env_logger

### ISSUE THREAD

**Issue by johnthagen** [rust-lang-nursery/log#107]
When building `rustfmt` on stable 1.16.0 the build time is very slow (~230 seconds on a quad-core 4GHz Sandy Bridge on Windows), and it appears the majority of time is spent building `env_logger`.

I observed similarly long build times on a quad-core, modern macbook pro laptop.

Not sure if this is `env_logger` specific or a `rustc` issue but just wanted to report the issue.

Is this expected?

**Comment by sfackler** [comment]
Cargo builds multiple crates in parallel. The last line in the output is just the last one that *started* to build, not the one that's currently building. If you look above you'll see `syntex_synatx` which is probably what's actually running.

**Comment by johnthagen** [comment]
@sfackler Thanks for the clarification, I hadn't realized that. I found [another comment](https://github.com/rust-lang/cargo/issues/1774#issue-92205005) referencing slow build times for `syntex_syntax` as well.

In any case, I'll close this issue.
