### ISSUE TITLE
env_logger performance, eliminating overhead of unused logging calls

### ISSUE THREAD

**Issue by Boscop** [rust-lang-nursery/log#112]
Quoted from here: https://github.com/google/tarpc/issues/139
> an interesting observation: we get ~10-20% higher throughput by removing all the debug logging calls in tarpc
> things like trace! compiles to a memory load and a branch in the final code, which actually ends up mattering for common calls
> I know slog (https://github.com/slog-rs/slog) has unused logging calls be completely compiled away
> and also compose a bit more nicely

tarpc uses env_logger. Is is possible to keep the semantics of env_logger the same while optimizing the log calls so that unused logging calls are also completely optimized away?

**Comment by dpc** [comment]
AFAIK `log` has exactly same logging statements, it's just using different defaults (I'm the author of `slog` and I just mimicked the whole mechanism of `log` altogether). While `slog` defaults to `info` for release and `debug` for debug builds, `log` defaults to `trace` everywhere. You can just change it manually using crate features defined here: https://github.com/rust-lang-nursery/log/blob/master/Cargo.toml#L20

**Comment by sfackler** [comment]
Yep, this is exactly why those Cargo features exist.

**Comment by alexcrichton** [comment]
Sounds like this is all possible! In that case closing
