### ISSUE TITLE
Support construction of `Record`s and `Metadata` 

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#116]
Testing and "shim loggers" typically want to do this so we should support these constructions! We probably want to have the construction go through builders to ensure that we can flexibly add more fields in the future. 

I'm not tagging this issue as "easy" just yet as it's got some API design involved, but if we get a concrete design listed here I think it'd be great to tag this issue as "easy" afterwards for an implementation to come by.

**Comment by rap2hpoutre** [comment]
@alexcrichton Since `LogRecord` and `LogMetadata` were renamed, could you edit the title and replace:

 > 'Support construction of `LogRecord`s and `LogMetadata`

By:

> Support construction of `Record` and `Metadata`

It's not really important, but I think it may confuse users (including me!).

**Comment by sfackler** [comment]
Fixed!

**Comment by omh1280** [comment]
I'll begin working on this!

- Create `RecordBuilder` and `MetadataBuilder` structs
- `impl` the following setters for `MetadataBuilder`:
  - `level()` and `target()`
- `impl` the following setters for `RecordBuilder`:
  - `args()`, `metadata()`, `location()`
- `impl` a `build()` method for each `Builder` and returns a `Record` or a `Metadata`
- Update the docs to specify that the use of these builders is for testing and "shim loggers" 

Look ok?

**Comment by brson** [comment]
@omh1280 that looks reasonable to me. Methods should probably take `&mut self`.

**Comment by omh1280** [comment]
I'm not sure how to give an example for creating a [`Location`](https://github.com/rust-lang-nursery/log/blob/master/src/lib.rs#L779). It's accessible (`pub`), but it's hidden from the docs and I think giving an example using it would be a bad decision. It's also a necessary part of constructing a full `Record`.

Does `Location` need a builder, too?

**Comment by sfackler** [comment]
Yep

**Comment by omh1280** [comment]
I've submitted a PR for this!

**Comment by brson** [comment]
Thanks @omh1280! Sorry for the delay 👍
