### ISSUE TITLE
Remove logger shutdown

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#117]
This adds some complexity to the logger plus extra cost on all logger calls. In our discussion of this issue the review team also concluded that it would be prudent to maybe add a top-level flushing method to explicitly ensure that a common part of shutdown, flushing, can still be manually performed. Flushing would be a noop by default.

**Comment by danielscottt** [comment]
Hi all,

I'm interested in diving into this one, but I could use a little guidance.  Is this about exposing a `flush`, or removing `shutdown`?  Or, rather, is it about removing the state (and therefore the check) from the logger's state machine?

Thanks!

**Comment by sfackler** [comment]
All of the above! Removing shutdown allows https://github.com/rust-lang-nursery/log/blob/master/src/lib.rs#L264 and the related logic to go away. Flush is just a new method on `Log` with a default implementation.
