### ISSUE TITLE
FromStr impls for LogLevel, LogLevelFilter use () as error type

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#119]
These implementations should use a dedicated opaque error type rather than `()`, and this error should implement the `Error` trait.

**Comment by alisha17** [comment]
I will like to work on this issue.
Should i create an error! macro that implements Error trait ?

**Comment by alexcrichton** [comment]
@alisha17 oh looks like @nivkner is working on this in https://github.com/rust-lang-nursery/log/pull/156 already
