### ISSUE TITLE
Crate docs should mention the logging levels and corresponding macros

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#121]
Just a small overview of what's possible.

**Comment by jesusbv** [comment]
Hi, I would like to help with this

**Comment by dtolnay** [comment]
Great! Let us know if you get stuck.

**Comment by jesusbv** [comment]
Thanks for letting me help. 

I will let you know :-)

Also, I'm new to Rust so any type of guidance is very welcome and appreciated.

**Comment by brson** [comment]
@jesusbv How's it going?

**Comment by jesusbv** [comment]
Well, I started checking all code but dont know where to start really
any hint about what the goal or output should be, that would help me a lot

P.S: Sorry for any inconvenience, i want to help but im new to this

**Comment by brson** [comment]
The levels are "error", "warn", "info", "debug", and "trace", in that order.

I think it would be appropriate for the "Use" section of the documentation, before it talks about the differences between libraries and executables, to explain that basic use of the libarary is through the `error!`, `warn!`, etc macros, linking to their definitions, that these macros accept formatting strings similarly to `println!`, linking to that macro.

**Comment by jesusbv** [comment]
@brson Thanks for the response and help, that gives me some guidance.
