### ISSUE TITLE
LogMetadata doc improvements

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#128]
- How are these values created?
  - Are these for logger implementors or log user?
  - Add an example

**Comment by MarkMcCaskey** [comment]
Hello!  I'd like to try to do this.  I'll submit a pull request for review later today.

**Comment by dtolnay** [comment]
Great, thank you!

**Comment by MarkMcCaskey** [comment]
Okay, first draft is at #177

**Comment by dtolnay** [comment]
Fixed in #177.
