### ISSUE TITLE
LogRecord doc improvements

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#129]
- How are these values created?
  - Are these for logger implementors or log user?
  - What's the difference between the 'level'/'target' accessors here
    and on the attached LogMetadata?
  - Add an example

**Comment by jehiggs** [comment]
Hey! I'd like to have a go at this, so long as it's not taken already?

**Comment by dtolnay** [comment]
Thanks, go for it @jehiggs.

**Comment by jehiggs** [comment]
Alright, pull request is [#178](https://github.com/rust-lang-nursery/log/pull/178)

**Comment by dtolnay** [comment]
Fixed in #178.
