### ISSUE TITLE
Use core not std

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang-nursery/log#13]
I believe everything in the logging interface just requires core, not std. (The `Box<Log>` could become a `Unique<Log>` as it is never deallocated.) This is important for allowing the interface to reach its full potential, e.g. serial port debugging before allocation is set up. https://github.com/rust-lang/bitflags was similarly changed to use core for the same reason.

If this sounds good, I would be happy to do the implementation work.

**Comment by Ericson2314** [comment]
Ah, missed the `rt::at_exit` call. Perhaps the use of `std`, `rt`, and `Box` could be controlled by a cargo feature?

**Comment by Amanieu** [comment]
I submitted a PR for this: #68
