### ISSUE TITLE
set_logger doc improvements

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#135]
- Add links
  - Add "Errors" section
  - Add example

**Comment by alexcrichton** [comment]
We should also clarify the error conditions here to mention there's no memory unsafety, but also clearly state what the error conditions are.

**Comment by rap2hpoutre** [comment]
@alexcrichton I already wrote (helped by rustaceans!) an example of use of `set_logger` for the cookbook here: https://brson.github.io/rust-cookbook/logging.html#log-messages-with-a-custom-logger

Do you think we have to write a new different one? Or "copy/pasting" this one is OK? Maybe we should make a shorter example, but I don't know what to remove.

**Comment by alexcrichton** [comment]
@rap2hpoutre nah copy/pasting sounds great! No need to create more work when it's already done :)

**Comment by rap2hpoutre** [comment]
@alexcrichton Ok done for the example part!

**Comment by alexcrichton** [comment]
Awesome! In that case closing.

**Comment by budziq** [comment]
@alexcrichton hi I would reopen as set_logger doc still misses links and errors section
