### ISSUE TITLE
Change html_root_url to https://docs.rs/$crate/$version

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#141]
in src/lib.rs

**Comment by morrme** [comment]
I can help with this.

**Comment by dtolnay** [comment]
Great! How is this going @morrme? Let us know if you get stuck.

**Comment by morrme** [comment]
@dtolnay Thanks! I was waiting for the go-ahead; just sent over a PR:

**Comment by dtolnay** [comment]
#168 did this for `log`. Reopening to do the same for `env_logger` as well.

**Comment by morrme** [comment]
would you like me to take care of that one too?

**Comment by dtolnay** [comment]
Yes please do.
