### ISSUE TITLE
Reduce "stuttering" in types

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#142]
Rename types like `log::LogRecord` to `log::Record`

**Comment by omh1280** [comment]
I'd like to try working on this. 

To confirm: 
`LogLevel` -> `Level` 
`LogLevelFilter` -> `LevelFilter`
`LogRecord` -> `Record`
`LogMetadata` -> `Metadata`, etc.?

Just types? What about functions like `log::LogLevel::to_log_level_filter()`? Should it become `log::Level::to_level_filter`?

Should `MaxLogLevelFilter` become `MaxLevelFilter`?

**Comment by alexcrichton** [comment]
That all sounds great to me @omh1280! @sfackler does anything else come to mind for you?

**Comment by sfackler** [comment]
That's everything I can think of. I would agree that the functions and `MaxLogLevelFilter` would be renamed as well.
