### ISSUE TITLE
Add serde impls for LogLevel/LogLevelFilter 

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#143]

**Comment by meven** [comment]
I would like some guidance before making a pull-request for this.
In your opinion, should it use #derive (with a optinal dependency) as documented https://serde.rs/derive.html or should it implement directly the Serialive and Deserialize impls as documented https://serde.rs/custom-serialization.html
I would favor the former as is avoids adding any dependency.

**Comment by dtolnay** [comment]
You will need at least Deserialize to be custom to match the case insensitive behavior of FromStr. And Serialize is only going to be a few lines so not worth pulling in serde_derive for that, in my opinion.

**Comment by dtolnay** [comment]
I filed #183 to follow up on whether all caps is the best choice for the Serialize impls.
