### ISSUE TITLE
Implement common traits for more types

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#144]
- LogLocation: Eq/PartialEq, Ord/PartialOrd, Hash, Clone
  - LogMetadata: Eq/ParialEq, Ord/PartialOrd, Hash
  - LogLevel: Hash
  - LogLevelFilter: Hash

**Comment by omh1280** [comment]
Hi Alex,
See #151 and let me know if it is OK!
- Ottavio
