### ISSUE TITLE
Inconsistent error Display and description() messages

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/log#166]
All of our Error types have slightly different Display and description() representations.

- SetLoggerError
  - display: attempted to set a logger after the logging system was already initialized
  - description: set_logger() called multiple times
- ShutdownLoggerError
  - display: attempted to shut down the logger without an active logger
  - description: shutdown_logger() called without an active logger
- LevelParseError
  - display: attempted to convert a string that doesn't match an existing log level
  - description: called from_str() on a string without a matching log level

Is this part of an existing convention to make Display more narrative and description() more technical? If not, how about we pick a consistent message for each error?

**Comment by sfackler** [comment]
I kind of doubt `Error::description` is used anywhere at all. It should be consistent with Display though.
