### ISSUE TITLE
Feature request: Logging only for testing

### ISSUE THREAD

**Issue by derekdreery** [rust-lang-nursery/log#18]
It would be good to have a macro which does a println/log during testing, but is removed when not testing.

Another alternative would be a log statement which is removed when ndebug is set.

**Comment by derekdreery** [comment]
Or am I misunderstanding?

**Comment by jimmycuadra** [comment]
I'm wondering about this as well. I'm building a library that uses Hyper, and I want to run my tests with Hyper's logs turned on, but it's not obvious how to initialize env_logger within the test suite.

**Comment by jonas-schievink** [comment]
I want this too, this would make testing much easier. It would be great if the default log level would be set to `DEBUG` when `cfg(test)` is active.

**Comment by KodrAus** [comment]
I think this is a bit out-of-scope for `log`, but definitely something we could look at supporting more smoothly in `env_logger`, or another alternative crate specifically for logging in tests.

We've had a few years without activity here so I'll go ahead and close this one now as out-of-scope, but please leave a comment if there's something new to add!
