### ISSUE TITLE
Consider rustfmt

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/log#182]
Moved from https://github.com/rust-lang-nursery/log/issues/150#issuecomment-304629732:

> Could we make `rust fmt` mandatory for this crate ?

**Comment by dtolnay** [comment]
I agree with using rustfmt.

I generally disagree with requiring rustfmt for a build to pass. The tradeoff is scaring away new contributors. If someone makes a PR, I would prefer that they remember it as a reasonable discussion about meaningful things, rather than as a struggle to satisfy a grumpy buildbot. If the code looks mostly fine then nobody will notice or care anyway. Somebody can run rustfmt every month or so and it takes 10 seconds to clean everything up, so there isn't really anything to gain from enforcing it in the build.

**Comment by meven** [comment]
Well your take was more accurate to what I intended.
My idea was in fact to find a way to ensure the code was formated.
I use rustfmt regularly and when I used it on this crate in a branch, it touched a lot of lines that did not need to be formated and made my commit noisy.
I feel your idea of behind the scene occasional formating a better solution.
