### ISSUE TITLE
Standardize on capitalization of log levels

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/log#183]
The Display impl generates all caps.

```rust
assert_eq!("INFO", LogLevel::Info.to_string());
```

But all the env_logger example code uses lowercase.

```
$ RUST_LOG=info ./main
```

The FromStr impl is case insensitive so this is fine, but it makes it hard to pin down which one makes more sense for the Serialize impl to generate (#143).

**Comment by daboross** [comment]
I'd think it fairly reasonable to have all configuration and documentation name levels with all lowercase, and have any end-user-displaying be all uppercase. I think a distinction between configuration&documentation vs. logging display clarifies this some - but then should the Display implementation assume that it's being passed to an end user/logger?

**Comment by brson** [comment]
No progress here. Do we want to make any changes?

**Comment by daboross** [comment]
I would be inclined to believe the current behavior is the best solution. `Display::fmt`, for directly displaying log levels, is all-caps, and everything configuration related (Serialize, Deserialize, examples, etc.) is lower case.

**Comment by alexcrichton** [comment]
I'd also be fine with the current behavior as @daboross mentioned

**Comment by sfackler** [comment]
👍

**Comment by ahmedcharles** [comment]
Shouldn't this be closed now?
