### ISSUE TITLE
add new log level Request/Access

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang-nursery/log#202]
Many application have some concept of a request, which may need special handling when logging.

A use case for this is a webserver which normally logs to standard error, but logs requests to standard out, so they can be processed separately. For example Nginx has configuration for [`access_log`](http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log) (requests) and [`error_log`](http://nginx.org/en/docs/ngx_core_module.html#error_log) (other messages).

The name could be `Request` or `Access`, I don't have a preference.

**Comment by Thomasdezeeuw** [comment]
Any opinions?

**Comment by sfackler** [comment]
The example of Nginx is a bit different since that's a custom logging thing made just for Nginx. I'm not sure this makes sense for a general purpose logging framework. Do you know of any general purpose frameworks that have these levels?

How are `Request`/`Access` ordered in verbosity with respect to the other levels?

**Comment by Thomasdezeeuw** [comment]
I think most server side applications have some sense of requests, Nginx (or webservers in general) was just an example. I don't think a lot of general purpose frameworks have a special level for this. However I still think it would be usefull.

As for the ordering, in my pull request #205 I put it at the top as a special level. This way it can be treated in a special way by the log implementation, alternatively it could be put above the `Info` level. That, along with a possible cargo feature for enabling or disabling it akin `max_level_error`, could use more discussion.

**Comment by sfackler** [comment]
Many server side applications have some sense of requests, but one that I'm aware of have a special log verbosity level for them. They tend to either log to a special target (`server.requests` or whatever), or just don't use the normal logger for request logs. IME it tends to not fit into normal logging all that well. You commonly don't want the normal formatting applied to other log events, for example.

**Comment by Thomasdezeeuw** [comment]
I agree that you generally don't want the same formatting to you request log as the other logs. However some sort of standardized logging for request would be great. Maybe that can be achieved using a special target, or even a macro that just calls `info!(target = "server.requests", ...)` or something along those lines.

My main goal is to indentify request logs in the logging implementation, but let general implementations (e.g. `env_logger`) still work.

**Comment by sfackler** [comment]
I'm still not totally sure why this needs to be handled that the level of the `log` crate?

**Comment by Thomasdezeeuw** [comment]
My main goal is having a standard. But that could be handled outside of the crate.

**Comment by Thomasdezeeuw** [comment]
Since nobody else seems interested I'm going to close this and use @sfackler idea of using a special target instead.
