### ISSUE TITLE
Rename set_logger_raw to try_set_logger_raw

### ISSUE THREAD

**Issue by alisha17** [rust-lang-nursery/log#204]
With respect to the changes made in #187, it makes sense to change set_logger_raw to panic on error (just like set_logger); where set_logger_raw panics on error and try_set_logger_raw returns error.

@alexcrichton @dtolnay

**Comment by alexcrichton** [comment]
The rationale to change `set_logger` to panic-on-error was that most libraries would transitively call it through their logger's initialization function. I'd imagine, however, that `set_logger_raw` is quite rarely called, so I'd actually advoate for renaming `set_logger_raw` to `try_set_logger_raw` and *not* adding a panicking variant of `set_logger_raw`

**Comment by alisha17** [comment]
@alexcrichton So should I go ahead with renaming set_logger_raw to try_set_logger_raw?

**Comment by alexcrichton** [comment]
Sure!
