### ISSUE TITLE
Support integrating foreign loggers

### ISSUE THREAD

**Issue by stephaneyfx** [rust-lang-nursery/log#206]
Some libraries (e.g. Qt) offer the ability to install hooks that are invoked when the library logs something. It would be nice to be able to redirect these foreign log messages to the Rust logger, and this is already somewhat doable, if one is willing to give up on the original location information or stuff it in the message text. The issue is that `Location`'s `__module_path` and `__file` are of type `&'static str`. Foreign libraries may have non-static location strings or even if they are static, they may not be in UTF-8 and thus require a dynamic conversion.

I think changing the definition of `Location` to the following would be a more versatile solution:

```rust
pub struct Location {
    pub __module_path: Cow<'static, str>,
    pub __file: Cow<'static, str>,
    pub __line: u32,
}
```

This allows to generate dynamic location strings, but does not require a dynamic allocation when the location strings are `'static`.

Since #200 has not been merged yet and thus `LocationBuilder` has not been released, the only breakage is that `Location` is not `Copy` anymore. But isn't it acceptable considering that there is already a breakage with the name change from `LogLocation` to `Location`?

What do you think? Do you have other suggestions to integrate foreign loggers? If the idea I described is considered good, I can work on it, once PRs like #200 are merged.

Thank you.

_Note: Such integration also requires some kind of `LogBuilder` like what [@alexcrichton suggested](https://github.com/rust-lang-nursery/log/issues/95#issuecomment-243556841)._

**Comment by sfackler** [comment]
Using Cow would cause problems in no_std crates - we should be able to change the `&'static str`s to `&'a str`s though. That will mean that the location etc will no longer have a `'static` lifetime but that's usually not a problem, and you can always make your own `OwnedLocation` and reconstruct a `Location` from that when necessary.

**Comment by stephaneyfx** [comment]
Thank you for explaining. Is there already somebody working on the approach you outlined? If not, I can look into it, but I guess it is probably better to wait for #200 to be merged as it would no longer build otherwise. What do you think?

**Comment by whitequark** [comment]
I wrote a library intended to address exactly this issue: https://github.com/m-labs/rust-managed#usage

**Comment by dpc** [comment]
Wouldn't `&'a fmt::Display` do?

**Comment by sfackler** [comment]
@alexcrichton the encoding conversion case is an interesting one wrt our discussion on #rust-libs yesterday.

**Comment by alexcrichton** [comment]
Interesting and good point! We may need to go to `'a` sooner than we thought...

**Comment by XX** [comment]
@alexcrichton @sfackler @dpc How about using `Cow<'static, str>`-like module_path and file? Current solution with `'a str` does not allow `slog` + `slog-async` + `slog-stdlog` work correctly, because `slog::RecordLocation` must be `static`.

https://github.com/slog-rs/stdlog/pull/9
https://github.com/slog-rs/stdlog/pull/5

**Comment by sfackler** [comment]
Why would the design of `log::Record` matter for slog's internal APIs? It can store them however it wants and then just translate to a borrowed `log::Record` right when it transfers over to log, right?

**Comment by XX** [comment]
@sfackler For async logging, we need to transfer `Record`-data to another thread, so we can use owned data or `'static` borrowed data. In fact, in most cases `module_path` and `file` are initialy `&'static str`, but the `log::Record` always reduces theirs lifetimes to `'a`. So it forces us to allocate memory for these strings every time when logging :(

Getting static module_path and file:
```rust
macro_rules! log {
    (target: $target:expr, $lvl:expr, $($arg:tt)+) => ({
        let lvl = $lvl;
        if lvl <= $crate::STATIC_MAX_LEVEL && lvl <= $crate::max_level() {
            $crate::__private_api_log(
                __log_format_args!($($arg)+),
                lvl,
                &($target, __log_module_path!(), __log_file!(), __log_line!()),
            );
        }
    });
    ($lvl:expr, $($arg:tt)+) => (log!(target: __log_module_path!(), $lvl, $($arg)+))
}
```
Pass module_path and file with a reduced lifetime to logger:
```rust
pub fn __private_api_log(
    args: fmt::Arguments,
    level: Level,
    &(target, module_path, file, line): &(&str, &str, &str, u32),
) {
    logger().log(
        &Record::builder()
            .args(args)
            .level(level)
            .target(target)
            .module_path(Some(module_path))
            .file(Some(file))
            .line(Some(line))
            .build(),
    );
}
```

**Comment by sfackler** [comment]
Ah, that makes sense. Rather than changing to `Cow<'static, str>` (static str vs owned string), we could go to an enum of static str vs borrowed str. We could support that by adding a couple of new setters in the builder type for `target_static`, `module_path_static`, etc, and accessors on `Record` that return `Option<&'static str>`. That would maintain back compat but let you avoid allocating in the common case.

**Comment by XX** [comment]
@sfackler Yes, I think this is a good solution.

**Comment by KodrAus** [comment]
As of `log` `0.4.8` you can now call `Record::module_path_static` and `Record::file_static` to attempt to get a `&'static str` out of them. `Record`s created using the `log!` macros will have static strings.
