### ISSUE TITLE
env_logger::Builder example does not compile

### ISSUE THREAD

**Issue by kahing** [rust-lang-nursery/log#209]
The code in https://rust-lang-nursery.github.io/log/env_logger/struct.Builder.html does not compile:

```
Compiling playground v0.0.1 (file:///playground)
error[E0432]: unresolved import `log::Record`
 --> src/main.rs:6:11
  |
6 | use log::{Record, LevelFilter};
  |           ^^^^^^ no `Record` in the root

error[E0432]: unresolved import `log::LevelFilter`
 --> src/main.rs:6:19
  |
6 | use log::{Record, LevelFilter};
  |                   ^^^^^^^^^^^ no `LevelFilter` in the root. Did you mean to use `LogLevelFilter`?

error[E0432]: unresolved import `env_logger::Builder`
 --> src/main.rs:7:5
  |
7 | use env_logger::Builder;
  |     ^^^^^^^^^^^^^^^^^^^ no `Builder` in the root
```

I get the same error when trying to use the builder in my own project locally.

**Comment by omh1280** [comment]
Hi @kahing,

You're looking at the very latest `env_logger` docs, which include major changes to the naming of structs in `log` and `env_logger`. Look here for docs that match your `env_logger` version: https://docs.rs/env_logger/0.4.3/env_logger/struct.LogBuilder.html

The naming changes happened in #162, if you're curious.

Sorry about that!

**Comment by kahing** [comment]
ok
