### ISSUE TITLE
env_logger ignores binary name with minus, only accepts underscore

### ISSUE THREAD

**Issue by SuperFluffy** [rust-lang-nursery/log#210]
I have a binary with the name `foo-bar`. When setting the environment variable `RUST_LOG=foo-bar=debug ./foo-bar`, the `env_logger` does not write anything. Changing this to `RUST_LOG=debug` reveals that I need to pass `RUST_LOG=foo_bar=debug ./foo_bar` for the setting to be picked up.

It looks like `env_logger` follows the rust module naming convention and not the actual binary name in `Cargo.toml`.

Is this intended? Can it be changed? The [current formulation](http://rust-lang-nursery.github.io/log/env_logger/) in the API docs is a bit confusing in that regard:

```
Assumes the binary is main:
```

**Comment by daboross** [comment]
This could be solved by env_logger's setup code replacing all instances of `-` with `_` - not sure if that's what we want to do though.

The main problem here is that `log`, and thus `env_logger`, rely on the https://doc.rust-lang.org/std/macro.module_path.html macro, which, as you can see, transforms library/binary crate names from dash form to underscore form.

**Comment by KodrAus** [comment]
I think it's reasonable to normalise the path passed to filter if that's what's going to be matched anyways. I'm not sure if there's anything else we could do.

**Comment by sfackler** [comment]
env_loggers has moved out of this repo!
