### ISSUE TITLE
Proposal: provide a public constructor for LogRecord

### ISSUE THREAD

**Issue by BusyJay** [rust-lang-nursery/log#223]
Sometimes we may need to unify the log across c ABI. But LogRecord is constructed from macro, there seems to be no way to bridge the c log and rust log without losing the file and line information even if c libraries provide hooks.

**Comment by sfackler** [comment]
This is already implemented on master, but hasn't made it into a release yet: https://github.com/rust-lang-nursery/log/blob/master/src/lib.rs#L709.

**Comment by BusyJay** [comment]
Will there be a release anytime soon? Since last release is 4 months ago.

**Comment by sfackler** [comment]
Yep, there should be a release before the end of the year, and hopefully sooner than that. There are  a couple of final details to work out.

**Comment by BusyJay** [comment]
Thanks for the quick reply. Looking forward for it!
