### ISSUE TITLE
Bad link on crates.io

### ISSUE THREAD

**Issue by funkill** [rust-lang-nursery/log#225]
Link "log documentation" on crates.io goes to https://doc.rust-lang.org/log/log/index.html and says what page not found

**Comment by smt923** [comment]
By the looks of it this was fixed in 8af5f3c, probably just needs a new release to be pushed to crates.io

**Comment by KodrAus** [comment]
Thanks for reporting this @funkill and for investigating when it was fixed @smt923!

When the next major version lands on `crates.io` this will be fixed up automatically so I'll close this issue. I'm not sure it's worth cherry-picking to the `0.3.x` branch at this stage, but please leave a comment if you think I'm wrong there!
