### ISSUE TITLE
Possibly removing closures from `set_*_logger` functions?

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#243]
Are the closures still needed any more? (I'm probably missing some historical context).

I could imagine that we don't have closures here but rather just parameters along with a free function that sets the max level (at any time). Although maybe there's a downside to configuring the max log level (globally) at any point in time?

**Comment by sfackler** [comment]
The closure-based indirection is there to make sure the active logger is the only thing that can mess with the max log level, yeah. The main downside is that random code could come in and poke the max log level in confusing ways, but maybe that's not enough of an issue that we need to worry about the extra weirdness?

**Comment by alexcrichton** [comment]
Hm yeah I wouldn't personally be too worried about a downside like that. The handling of races between concurrent initialization is mostly just for safety rather than anything else, I don't think anyone really wants to rely on log's own arbitration. In that sense I'd fine the argument-taking apis a little more ergonomic (no need for an extra closure) and a little more flexible perhaps (update the max log level while the program is running).

**Comment by sfackler** [comment]
> (update the max log level while the program is running)

As the logging implementation, you can already do this by saving off the token and using it later. Removing the closure would allow things other than the logging implementation to do it as well if they wanted to.

**Comment by alexcrichton** [comment]
Ah true yeah, the maybe it's just ergonomics!
