### ISSUE TITLE
Add a note about minimal required Rust version.

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang-nursery/log#252]
Looks like since v0.4 it's 1.16.

**Comment by BurntSushi** [comment]
Actually, it looks like it's 1.16 as of `0.3.9`, which leads to things like this https://github.com/rust-lang-nursery/rand/commit/85ceba8d82e35a591717824c40bca26120856ae3 --- Perhaps avoiding ecosystem wide churn is worth it though.
