### ISSUE TITLE
Documentation link on https://crates.io/crates/log is a 404.

### ISSUE THREAD

**Issue by remram44** [rust-lang-nursery/log#254]
`Cargo.toml` says `"https://docs.rs/log"` but somehow crates.io links to `https://doc.rust-lang.org/log`?

**Comment by remram44** [comment]
Interestingly, looking inside `log-0.4.0.crate`, the `Cargo.toml` is correct. Is this a crates.io bug?

**Comment by sfackler** [comment]
I think this'll be fixed by https://github.com/rust-lang/crates.io/pull/1207.

**Comment by roblabla** [comment]
The link works now. This issue can probably be closed.

**Comment by remram44** [comment]
https://doc.rust-lang.org/log appears to redirect now, and the 0.4.* crates point to `docs.rs`. Thanks!
