### ISSUE TITLE
Get thread name from record

### ISSUE THREAD

**Issue by dbrgn** [rust-lang-nursery/log#256]
Is there a way to access the thread name from a [Record](https://docs.rs/log/0.4.1/log/struct.Record.html)?

**Comment by sfackler** [comment]
We don't store the thread name in a Record, no.

**Comment by dbrgn** [comment]
That would probably be a case for structured logging, right?

**Comment by sfackler** [comment]
I don't really see what those have to do with each other?

**Comment by dbrgn** [comment]
I'd like to attach the thread name to logs. If there were a way to add structured data to logs, I could add thread_name=<name>. Unless I'm misunderstanding what structured logging is :)

Anyways, if you don't plan to add this, feel free to close the issue. Would be great if there were a better way to add information like thread names than concatenating strings though.

**Comment by sfackler** [comment]
The logger implementation can just grab the name of the thread. For example, in log4rs: https://github.com/sfackler/log4rs/blob/master/src/encode/json.rs#L77

**Comment by dbrgn** [comment]
Oh, thanks, I wasn't aware of that!
