### ISSUE TITLE
change logger at run time

### ISSUE THREAD

**Issue by kahing** [rust-lang-nursery/log#258]
I have a problem that I am not able to solve with the logging framework. I am writing a daemon that once it daemonizes, should log to syslog. But before that, it should log to stderr. Currently I am using env_logger which can only log to stderr. I can also use syslog which can only log to syslog. Ideally I want to be able to log to stderr until it parses all the command line arguments, and then daemonize and start logging to syslog if the arguments say so.

**Comment by sfackler** [comment]
The right way to do this would probably be to make a logger implementation that directs the messages to stderr or syslog depending on the situation.
