### ISSUE TITLE
`unexpected end of macro invocation` when passing no parameters to debug macro.

### ISSUE THREAD

**Issue by c-edw** [rust-lang-nursery/log#271]
When I pass no parameters to `debug!()`, like so,
```rust
debug!();
```
the program will exit with the error `unexpected end of macro invocation`. The expected behavior is that an empty line should be printed, as it is with `println!()`.

**Comment by sfackler** [comment]
I think the situation is a bit different here compared to println as different log lines are more separate than standard output is. Why do you want to log no information?

**Comment by c-edw** [comment]
It's an easy way of printing a line break.

**Comment by dekellum** [comment]
This might be of more obvious value with #296, e.g. logging with structured values only, and no unstructured message? 

Also an obvious workaround with current *log* is `debug!("")`, which works as expected.

Logging implementations could still decide, or be configured, to filter both `debug!("")`, any future supported `debug!()`, and `debug!("\n")` for that matter, if these log messages are viewed more an an abuse of the logging system.

**Comment by dekellum** [comment]
Also the error message for an empty log macro invocation, is now even stranger then the OP's title, see below. I would imagine, if this should remain a compile time error, that a PR would be favorable considered to improve the error message:

[Link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e84492e0c3f90c70da6bdf364df87f32):

``` txt
error: expected identifier, found `,`
 --> src/main.rs:9:5
  |
9 |     info!();
  |     ^^^^^^^^
  |     |
  |     expected identifier
  |     help: remove this comma
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
