### ISSUE TITLE
Feature request: Scope macros in prelude

### ISSUE THREAD

**Issue by mehcode** [rust-lang-nursery/log#272]
Using the Rust 2018 preview mode in nightly I find myself wanting to just import all the log macros in one go vs. having to name them explicitly.

```rust
// Current situation
use log::{log, info, error};

// Desired situation (only imports log macros)
use log::prelude::*;
```

**Comment by sanmai-NL** [comment]
The practice of using globs to specify items does not leave you with less cognitive load as author, but does add cognitive load for readers not yet familiar with the full set of log macros.

**Comment by tkilbourn** [comment]
I just ran into this, converting a medium-sized crate with lots of modules. `use log::macros::*;` would be acceptable to me as well, to call out that it's just the macros being imported.

**Comment by cavedweller** [comment]
I would also really like to have the macros namespaced so I could glob import them. This is not something I would expect to confuse people.

**Comment by alexcrichton** [comment]
The intention for the `log` crate in the near future is likely to take advantage of `#[macro_export(local_inner_macros)]` which won't need either a prelude module or a global import, and instead `use log::info` should work as expected.

**Comment by cavedweller** [comment]
@alexcrichton I think the comment here is that frequently we would frequently find ourselves with 

`use log::{warn, info, error}`, when actually all I want to do is `use log::*`, then I frequently find myself being disrupted from my workflow when I need to got add another log level (since I didn't import them all because of `deny(warnings)`.

I added `syslog::macros::*` for the Fuchsia syslog crate, and it works nicely.

**Comment by alexcrichton** [comment]
Ah ok, thanks for clarifying! Seems like a reasonable feature request to me!

**Comment by sanmai-NL** [comment]
@cavedweller and others reading that: a better way is to import all macros you ‘may’ use and allow unused imports on that import statement.

**Comment by cavedweller** [comment]
@sanmai-NL I think I disagree, for better or for worse, allows are significantly more confusing for a person onboarding to a codebase. They need to figure out what is special about that specific import, and then the statement doesn't get cleaned up when all the macros are actually all in use.

I don't think something like the import of logging utilities should not take two lines either.

**Comment by sanmai-NL** [comment]
Any static analysis policy exception should of course be documented in a comment. Not lcleaning the exception up would be proper in your case, it still applies, just happens to be inapplicable at some time, but could become applicable after a few changes. If you care about this then I’d suggest to just import what you use and change imports as necessary.

Complaining about the number of lines taken to achieve something (3 lines vs 1) is the kind of attitude that triggers me to put out this criticism. The job of a programmer is to produce quality software not type as little as possible (even though most of it is copy-paste, boilerplate stuff).

**Comment by KodrAus** [comment]
In the 2018 edition I find myself preferring the old `extern crate` approach for `log` so that the macros are always in scope:

```rust
#[macro_use]
extern crate log;
```

For macros like `log`'s that are peppered around a lot I think this is a low-friction way to go.

**Comment by mehcode** [comment]
I've come around to not want this feature request. With `extern crate` no longer needed, remember that crates are just right there, in scope in the 2018 edition.

```rust
log::error!("hello");
```

Thats how I strongly prefer my logs now.

**Comment by KodrAus** [comment]
Ah that's another way to do it :+1:

Since we have ways to do this in the released 2018 edition that are roughly the same ergonomics-wise as 2015 without needing a prelude I'll go ahead and close this one now, but please leave a comment/re-open if there's anything new to add!
