### ISSUE TITLE
Executable size impact

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang-nursery/log#275]
Here is a simple demo:
```rust
#[macro_use] extern crate log;
extern crate fern;

fn main() {
    fern::Dispatch::new()
        .level(log::LevelFilter::Warn)
        .chain(std::io::stderr())
        .apply().unwrap();

    warn!("Hello, world!");
//     println!("Hello, world!");
    test();
}

fn test() {
    warn!("Hello, world!");
//     println!("Hello, world!");
}
```

According to the `cargo-bloat`, the code size with `warn` in the release build is 1000B and with `println` - 717B. Why it impacts the size so much? Maybe this is a `cargo-bloat` bug (yes, I'm the author)?

In the real world applications, the results are even more drastic. For example, if I remove all the logging from [this](https://github.com/RazrFalcon/usvg/blob/master/src/convert/shapes.rs) module the size in the release build will be reduced from 9.1KiB to 3.1KiB. It's ridiculous.

I this is a correct behavior or am I missing something?

log v0.4.1
fern v0.5.5
cargo-bloat v0.5.0
rustc 1.26.1

**Comment by RazrFalcon** [comment]
Hmm... Interesting.

I was able to reduce the exe/crate size to the same size a bit.

- default log! - 275.3KiB
- custom log! - 270.2KiB
- minimal custom log! - 267.6KiB
- eprintln! - 266.7KiB

Custom:
```rust
#[inline(never)]
fn log_fast(level: log::Level, module: &str, file: &str, line: u32, args: ::std::fmt::Arguments) {
    if level <= ::log::STATIC_MAX_LEVEL && level <= ::log::max_level() {
        log::logger()
            .log(
                &log::RecordBuilder::new()
                    .level(level)
                    .target(module)
                    .args(args)
                    .module_path(Some(module))
                    .file(Some(file))
                    .line(Some(line))
                    .build(),
            );
    }
}

macro_rules! log {
    ($lvl:expr, $($arg:tt)+) => ({
        ::log_fast($lvl, module_path!(), file!(), line!(), format_args!($($arg)+))
    });
    ($lvl:expr, $($arg:tt)+) => (log!($lvl, $($arg)+))
}
```

Minimal:
```rust
#[inline(never)]
fn log_fast(level: log::Level, args: ::std::fmt::Arguments) {
    if level <= ::log::STATIC_MAX_LEVEL && level <= ::log::max_level() {
        log::logger()
            .log(
                &log::RecordBuilder::new()
                    .level(level)
                    .target("")
                    .args(args)
                    .module_path(None)
                    .file(None)
                    .line(None)
                    .build(),
            );
    }
}

macro_rules! log {
    ($lvl:expr, $($arg:tt)+) => ({
        ::log_fast($lvl, format_args!($($arg)+))
    });
    ($lvl:expr, $($arg:tt)+) => (log!($lvl, $($arg)+))
}
```

PS: surprisingly, removing the useless `trace!` from a [hot method](https://github.com/RazrFalcon/usvg/blob/23d3c4addddd40e3621add31ed70eed2fd9ca2f4/src/traits.rs#L186) reduced the size by 8% by itself with a default log implementation.

**Comment by sfackler** [comment]
That would make sense if the hot method was inlined in a bunch of places.

**Comment by RazrFalcon** [comment]
It was.

**Comment by sfackler** [comment]
You can also disable specific logging levels entirely at compile time, which will remove all of the code from the resulting binary, btw: https://docs.rs/log/0.4.1/log/#compile-time-filters
