### ISSUE TITLE
Documentation fix: are the max levels inclusive or exclusive?

### ISSUE THREAD

**Issue by golddranks** [rust-lang-nursery/log#279]
In the documentation, there is the following example:

> For example, a crate can disable trace level logs in debug builds and trace, info, and warn level logs in release builds with the following configuration:
> 
> `[dependencies]`
> `log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }`

However, there's clearly a mistake: it says that `max_level_debug` disables *trace* level logs, that is one level *below* debug, but `release_max_level_warn` disables up to *warn* level logs, which is the level mentioned in the feature name.

Which one it is?

Additionally, I find the name of the feature flag a bit unintuitive. They are a part of the crate API so it isn't easy to change, but consider this: surely the flag disables errors of priority level *below* the mentioned level and allows log messages of level *above*. But because you start allowing from the highest level downwards, using terminology like *max* is really confusing: is the flag talking about disabling from low priority levels, and the *max* level is the highest that is *still disabled*? If it would be about *allowing* that level, it surely would make more sense to talk about the *min* level that is allowed!

**Comment by KodrAus** [comment]
You're right, it can be a little unintuitive, because we consider `TRACE` to be a _higher_ logging level than `DEBUG`, rather than a lower one. So in order from lowest to highest it's:

- Error: 1
- Warn: 2
- Info: 3
- Debug: 4
- Trace: 5

So, `max_level_{level}` will include `{level}` and below. The `release_max_level_{level}` will do the same thing, but only for release builds.

**Comment by golddranks** [comment]
Thanks for the explanation! So, that makes the following in the above quote wrong: "trace, info, and warn level logs in release builds". It should be "trace, debug and info level logs in release builds".

**Comment by golddranks** [comment]
I sent a PR to elaborate the documentation: https://github.com/rust-lang-nursery/log/pull/280

**Comment by KodrAus** [comment]
Closed by #280
