### ISSUE TITLE
How to own a Record? Having trouble with fmt::Arguments

### ISSUE THREAD

**Issue by agrover** [rust-lang-nursery/log#282]
I'm working on a logger that acts as a "flight data recorder" -- it holds all log output until commanded to dump it all at once. I'm trying to have my FlightDataLogger compose over another Logger implementation. The problem I'm having is that I'm converting the data in Record to an owned structure (OwnedRecord) that can be stored in a collection, but there's no owned version of fmt::Arguments. I can convert it to a string, but then there's no way (that I can see) to get it back into a fmt::Arguments that I need to build a Record to call the embedded logger's log() function.

Opening this issue on the off chance this is a feature request in disguise. Thanks.

**Comment by KodrAus** [comment]
@agrover You should be able to use your materialized `String` to build some new `format_args` to pass to the inner logger. Assuming you have something like:

```rust
for owned_record in self.held_records.drain(..) {
    self.inner_log.log(RecordBuilder::new()
        .args(format_args!("{}", owned_record.args_string))
        // ...
        .build());
}
```

As a random aside, I think this kind of composition of `Log` implementations isn't very straightforward with `log` right now, since it just fills the role of a single smart callback, rather than as a cooperative link in a pipeline.

**Comment by agrover** [comment]
Tried that, ran into a weird error! See referenced issue.

**Comment by sfackler** [comment]
You have to use the Arguments in the same expression that creates it due to how it's implemented.

```rust
// doesn't work
let x = format_args!("{}", foo);
println!("{}", x);

// works
println!("{}", format_args!("{}, foo));
```

**Comment by agrover** [comment]
Ah ok! So I need to not create a let-binding to the Record and then pass it to log(), but do it all in one step. This works! Thanks @sfackler and @KodrAus ! Closing.
