### ISSUE TITLE
Some platforms don't support Atomic*

### ISSUE THREAD

**Issue by zklapow** [rust-lang-nursery/log#285]
Similar to rust-lang-nursery/futures-rs#842 `log` uses `AtomicUsize` but this makes it impossible to compile for `thumbv6m-none-eabi` because it lacks atomic primitives. It would be great to have a feature which disables the use of atomics so that `log` can be used on those platforms.

**Comment by sfackler** [comment]
Does thumbv6m-none-eabi have threading/support mutexes?

**Comment by zklapow** [comment]
unfortunately not its `no_std`

**Comment by sfackler** [comment]
We'll need some way of synchronizing access to the state here.

**Comment by dpc** [comment]
@zklapow Does it have a SWP instruction? http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dht0008a/CJHBGBBJ.html

**Comment by jonas-schievink** [comment]
This is the only line that poses a problem on thumbv6:

https://github.com/rust-lang-nursery/log/blob/b782a88236b1e827b3eb2e6ea062524d1215e198/src/lib.rs#L1166

Would you accept a pull request adding a `set_logger_unchecked` function that uses non-atomic operations for setting the global logger? It would be safe to call iff no other threads exist and interrupts are disabled.

**Comment by sfackler** [comment]
That seems plausible. Is there an easy way to distinguish targets that have a CAS?

**Comment by jonas-schievink** [comment]
Only via a `build.rs` that inspects the `TARGET` variable, I think. There's an experimental cfg `target_has_atomic`, but it's unstable (and might not help in this case). AFAIK the `build.rs` approach is also the only way to distinguish ARMv6 from ARMv7 and other useful things, so it's already in use.

**Comment by jendrikw** [comment]
Atomics should also be disabled for `thumbv4-none-agb` as defined in https://github.com/rust-console/gba/blob/master/thumbv4-none-agb.json

**Comment by jendrikw** [comment]
It might be better to guard `set_logger` with ` #[cfg(target_has_atomic = "cas")]`, as it's done for `compare_and_swap` (see https://doc.rust-lang.org/src/core/sync/atomic.rs.html#1398) instead of maunally listing the unsupported targets.
