### ISSUE TITLE
Avoiding potentially lost log messsages when INITIALIZING

### ISSUE THREAD

**Issue by sunfishcode** [rust-lang-nursery/log#286]
`set_logger_inner` is careful to initialize its log state once, even when called from multiple threads:

https://github.com/rust-lang-nursery/log/blob/48bdd5679448e0ec43a20fb0e6a86900dcdefddd/src/lib.rs#L1154

and `logger` uses a `NopLogger` if the state isn't `INITIALIZED`:

https://github.com/rust-lang-nursery/log/blob/48bdd5679448e0ec43a20fb0e6a86900dcdefddd/src/lib.rs#L1211

However, if the thread doing the initialization doesn't run fast enough, `STATE` might still be `INITIALIZING` when `set_logger_inner` returns in another thread, so there is a window in that other thread in which log messages could be lost.

Would it make sense to either:
 - Make `set_logger_inner` wait if `STATE` is `INITIALIZING` until it changes to `INITIALIZED`, so that the state is always `INITIALIZED` by the time it returns, or
 - Add a way for user code to wait until `STATE` is `INITIALIZED`, so that user code can opt to wait if it wishes to avoid dropping messages

?

**Comment by sfackler** [comment]
The only operation performed in the INITIALIZING state is writing two words to memory. The *vast* majority of the time the state will either be UNINITIALIZED or INITIALIZED when a log message is recorded, I don't think adding extra logic to handle the INITIALIZING case is really all that valuable.

**Comment by sunfishcode** [comment]
I am suggesting code which would run at `set_logger_inner` time, once per thread, so it wouldn't affect the vast majority of time.
