### ISSUE TITLE
Document how to use log crate with 2018 edition

### ISSUE THREAD

**Issue by dereckson** [rust-lang-nursery/log#294]
The readme currently considers 2015 edition is used.

For the 2018 edition, the macro_use attribute and the extern crate declaration are superseded by a direct use of the macro (without a final question mark).

As such the doc should explain how to import the macros in such case.

**Comment by arve0** [comment]
Release a patch-version to update docs.rs?

**Comment by dereckson** [comment]
@arve0 Yes, that's what 0da424552703 does.

**Comment by arve0** [comment]
Ah, I see. If you like, I can send a PR with updated docs.rs documentation?

Also, move order of 2015- / 2018-example? Or even remove 2015-edition?
