### ISSUE TITLE
Thread-local logging context

### ISSUE THREAD

**Issue by stepancheg** [rust-lang-nursery/log#306]
Thread-local information could be useful for debugging. Per-thread data could contain request id, peer IP, client username, request URL or something like that.

In log4j API is called [NDC](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/NDC.html). I think log library could have API to be used like this:

```
log::with_ndc(&format!("req_id={} peer_ip={}", req_id, peer_ip), || {
    ...
    info!("request started");
    ...
    info!("request completed");
    ...
});
```

Log libraries like `env_logger` could access that information and print it at each line:

```
DEBUG 2018-11-11T22:10:30Z module: req_id=26 peer_id=1.2.3.4 request started
DEBUG 2018-11-11T22:10:30Z module: req_id=26 peer_id=1.2.3.4 request completed
```

log4j also has MDC tool to update/access per-thread map of attributes ([MDC](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/MDC.html)), but I found it not very useful (logging configuration is too complicated just to output all known attributes).

CC #256

**Comment by sfackler** [comment]
This can be implemented externally, and already has! https://crates.io/crates/log-mdc

I'm not sure if there's much to be gained by inlining it into this crate.
