### ISSUE TITLE
expected function, found macro `transactions::tx_from_raw`

### ISSUE THREAD

**Issue by rakhmanu** [rust-lang-nursery/log#307]
Hi,
 I run this : 
fn tx_from_raw(
            &self,
            raw: RawTransaction,
        ) -> Result<Box<dyn Transaction>, 
            EncodingError> {
            let tx = transactions::tx_from_raw(raw)?;
            Ok(tx.into())
        }
However the compiler says did you mean transaction::tx_from_raw(raw)!  It should not be like that How to fix it ? Thanks for contribution to help me

**Comment by KodrAus** [comment]
Hi @rakhmanu, this issue tracker is specifically for the `log` library. You'll probably have more success asking your question in one of the general community forums, [you can find a list of them here](https://www.rust-lang.org/en-US/community.html#getting-started).
