### ISSUE TITLE
what is a facade?

### ISSUE THREAD

**Issue by donbright** [rust-lang-nursery/log#310]
hello.

the main page says 'log is a facade'. what is that? is it a rust keyword? 

i have spent an hour trying to find a 'hello world' example for logging and i cant find one that actually works properly, so im trying to understand what im supposed to be doing, but the word 'facade' doesnt appear to have an explanation in the rust language book,  so im not sure what im supposed to be doing.... thanks for any help

**Comment by sfackler** [comment]
The log documentation discusses this: https://docs.rs/log/0.4.6/log/

**Comment by LeDominik** [comment]
But there's a point here: for me as a software developer a facade is a clear thing, just like e.g. slf4j -- but maybe the first sentence in the documentation should be more beginner-friendly.

Trying myself on a suggestion: _A Rust library providing a lightweight logging facade, that is a unified interface that is shared among various loggers in the Rust ecosystem. Try `env_logger` for basic stdout based logging, or check out more advanced compatible logging libraries (link)_

**Comment by donbright** [comment]
thanks, i appreciate it.
