### ISSUE TITLE
Memory leak within `set_boxed_logger`

### ISSUE THREAD

**Issue by danielhenrymantilla** [rust-lang-nursery/log#314]
The current choice of the global static logger being simply a pointer to a **static** `Log` requires that [`set_boxed_logger`](https://docs.rs/log/0.4.6/src/log/lib.rs.html#1094-1096) **leak** memory:

```rust
pub fn set_boxed_logger(logger: Box<Log>) -> Result<(), SetLoggerError> {
    set_logger_inner(|| unsafe { &*Box::into_raw(logger) })
}
```

The only way for a user to get around this is by using the following "hack" (which requires an additional layer of vtable indirection): [https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e8b9aebe507844f916a56f62529d5feb](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e8b9aebe507844f916a56f62529d5feb)

However, there is a way for the `::log` crate to handle both pointer to static memory and pointers to heap/managed memory, in the [same fashion as with `&'static str` vs `String`](https://llogiq.github.io/2015/07/10/cow-redux.html) (actually `Box<str>`) : using `Cow<'static, dyn Log>` instead of just `&'static dyn Log`

**Comment by sfackler** [comment]
What would the behavioral change be if the internals used a Cow instead of a &'static Log?

**Comment by danielhenrymantilla** [comment]
It would allow for both `&'static (dyn Log)` and `Box<dyn Log>` to be stored in the global mutable static var, while also ensuring the memory is freed right before the program exits, when in the `Box<dyn Log>` case.

Given that `Cow<'_, T> : Deref<Target = T>`, there is a big chance that no more code would need to be changed (just a need to call `.into()` when storing into the static var).

It should be noted, however, that `Cow<'_, T> : Deref<Target = T>` works by performing a pattern-match on the `Cow` enum (i.e. a C-`switch` on a tag) before providing a reference to a `dyn Log`. In other terms, it would add a single comparison operation on all logging actions. That still seems a pretty low cost to pay for avoiding the memory leak.

It could also allow to set the global static logger more than once, even while using multiple boxed loggers (which is currently made impossible to avoid a memory leak happening each time a boxed logger is set).

**Comment by sfackler** [comment]
Destructors don't run for statics on program exit.

**Comment by sfackler** [comment]
> Still, a `Cow<'static, dyn Log>`-like type provides **the right semantics**, even if there is no behavioral change at the moment (but imagine getting at some point destructors running for statics).

The semantics of a system *describe* its behavior. Storing a Cow just seems like would mislead people into thinking that the destructor will run when that's not the case.

There is a ~0% chance that the language will ever begin running code after program termination. An older version of the library added an atexit handler that dropped the logger, but running code at that time is a very dubious proposition.

**Comment by labyrinth-ssr** [comment]
We have noticed that log uses a global mutable static variable to ensure the one-time initialization. However there comes minor imperfection that the call of `Box::into_raw(logger)` will permanently cause memory leak.

Another design method may add a 'finalize' function for LOG and enables automated deallocation, excuted when exiting, or provide a manual destruction API exposed for users to call.

For automatically release, we've found one crate from crates.io that shares the same idea for lazy. ([staticinit](https://crates.io/crates/staticinit)) that can do the finalization for mutable static to release memory on heap when not being used. 
Here gives an toy example:
```Rust
impl Finaly for &dyn Log {
    fn finaly(&self){
         Box::from_raw(self); // execute when exit
    }
}

#[dynamic(finalize)] //finalize execute at program exit
static mut LOGGER: &dyn Log = &NopLogger;
```
For provide manually release interface:

```Rust
pub unsafe finalize(logger){
      // free the logger;
      // may be users can de-initialize log and register again
}
```

**Comment by Thomasdezeeuw** [comment]
@labyrinth-ssr the logger isn't always set via the boxed version calling `Box::from_raw` on it would be UB. You can also use [`set_logger`](https://docs.rs/log/latest/log/fn.set_logger.html) and manage the allocation yourself.

**Comment by danielhenrymantilla** [comment]
Note that the use of `Box` should not be that necessary; consider using a `static` with, _e.g._, a `sync::OnceCell<YourLogger>` in order to obtain a `&'static impl Logger` without involving a heap "leak":

```rs
fn set_logger(your_logger: YourLogger) -> Result<(), SetLoggerError> {
    use ::once_cell::sync::OnceCell;

    static STATIC_SLOT: OnceCell<YourLogger> = OnceCell::new();

    set_logger(STATIC_SLOT.get_or_init(|| your_logger))
}
```

in fact, with `type_alias_impl_trait`, one could even write a macro to do this very thing with support for generics inside the `YourLogger`:

```rs
type YourLogger = impl Log;

static SLOT: OnceCell<YourLogger> = OnceCell::new();

set_logger(SLOT.get_or_init(|| -> YourLogger { your_logger }));
```
