### ISSUE TITLE
Making `LogFilter::from_usize()` public 

### ISSUE THREAD

**Issue by elichai** [rust-lang-nursery/log#318]
Hi,
I'm using https://github.com/TeXitoi/structopt for CLI arguments and it has a nice feature called `from_occurrences` that it counts the number of `v`s when I pass `-v` and gives me a usize/u8.
I'm using that to select the `LevelFilter` for my logger.

Right now I have my own match, but it would be nicer if I could use the already existing `LogFilter::from_usize()` function (here: https://github.com/rust-lang-nursery/log/blob/master/src/lib.rs#L487 ) to convert it.
That way I won't need to worry about future changes to the LogFilter.

What do you think?
Thanks.

**Comment by elichai** [comment]
Hmm Ok, that's too bad. 
I do think that other people had to write a function like this too, but thanks anyway :)

**Comment by KodrAus** [comment]
No problem, thanks again for the suggestion! This might be something we could revisit in the future.
