### ISSUE TITLE
ATOMIC_USIZE_INIT deprecated in rust 1.34

### ISSUE THREAD

**Issue by dekellum** [rust-lang-nursery/log#320]
On to the next build warning...

https://travis-ci.com/rust-lang-nursery/log/jobs/174845625#L448
> warning: use of deprecated item 'core::sync::atomic::ATOMIC_USIZE_INIT': the `new` function is now preferred

`AtomicUsize::new` became usable as a const fn in 1.24, as best I can tell, so there are two options to fix this:

(a) Increase `log`'s MSRV to 1.24 and use `AtomicUsize::new`

(b) Introduce a build script with version_check (build dep) and cfg switch to `AtomicUsize::new` for >= 1.24

Or, I suppose: (c) ignore it.  Thoughts?

**Comment by sfackler** [comment]
`#[allow(deprecated)]`

**Comment by dekellum** [comment]
Ok lets call that option (d).  With all due respect, I am least pleased with (d) since it hides the upgrade nudge, until it breaks.   But that said, its also rather lame that all of (b) is required to cfg use the newer const fn with >= 1.24.

**Comment by sfackler** [comment]
> until it breaks

`ATOMIC_USIZE_INIT` will never break.

> But that said, its also rather lame that all of (b) is required to cfg use the newer const fn with >= 1.24.

How will a user of this library be better off if it uses the const constructor for this value?

**Comment by dekellum** [comment]
I presume you prefer (d) to either (a) or (b) then, ok. 

Seems like the your last question would be better made to whomever did the deprecation in `std` in the first place.  As a user I have to assume it was deprecated for some good reason and will therefore be removed in a future release. 

But rust-lang/rfcs#2523 would have had to be stabilized by rust 1.16 to make (b) trivially simple, and I guess I can understand your position in terms of risk-benefit.

**Comment by sfackler** [comment]
Deprecated stable APIs will not be removed from the standard library.
