### ISSUE TITLE
Description of compile-time log filtering needs clarification

### ISSUE THREAD

**Issue by vmalloc** [rust-lang-nursery/log#348]
Reading this: https://docs.rs/log/0.4.8/log/#compile-time-filters, I stumbled across this phrasing:

> Log invocations at disabled levels will be skipped and will not even be present in the resulting binary unless the log level is specified dynamically

I don't understand how this can be true -- either the call site is completely eliminated when release_max_level_XXX is used, or it isn't. If it is, I don't see how any dynamic logging adjustment can make it re-appear...

So the question boils down to - if I have a `trace!` invocation, and I set `release_max_level_debug`, what will be present in the final binary instead of that `trace` call? A condition check? nothing?

**Comment by sfackler** [comment]
Ah yeah, that sentence is wrong - the disabled levels are skipped entirely and dropped from the resulting binary.

**Comment by vmalloc** [comment]
@sfackler Just out of curiosity, where and how does that happen in the code?

**Comment by vmalloc** [comment]
I see this in the implementation:
```rust
#[macro_export(local_inner_macros)]
macro_rules! log {
    (target: $target:expr, $lvl:expr, $($arg:tt)+) => ({
        let lvl = $lvl;
        if lvl <= $crate::STATIC_MAX_LEVEL && lvl <= $crate::max_level() {
            $crate::__private_api_log(
                __log_format_args!($($arg)+),
                lvl,
                &($target, __log_module_path!(), __log_file!(), __log_line!()),
            );
        }
    });
    ($lvl:expr, $($arg:tt)+) => (log!(target: __log_module_path!(), $lvl, $($arg)+))
}
```
You rely on both level and the static being known to the compiler enabling it to elide the entire thing?

**Comment by sfackler** [comment]
Yep - the compiler will always eliminate `if false { ... }` expressions.
