### ISSUE TITLE
Allow env_logger to be initialised from user supplied spec

### ISSUE THREAD

**Issue by TimNN** [rust-lang-nursery/log#35]
In some situations it may be required / desirable to obtain the logging spec from some place other than an environment variable but still make use of the rest of `env_logger`'s functionality.

My current workaround manually sets the environment variable and then initialises `env_logger`:

``` rust
fn init_logging(spec: &str) {
    ::std::env::set_var("RUST_LOG", spec);
    ::env_logger::init().unwrap();
}
```

I think it would be much nicer (and trivial to support) if this could be written like this instead:

``` rust
fn init_logging(spec: &str) {
    ::env_logger::init_with_spec(spec);
}
```

**Comment by alexcrichton** [comment]
cc #29, a similar request there

**Comment by quadrupleslap** [comment]
Wait, doesn't the `LogBuilder` let you parse from whatever `&str` you want?

**Comment by TimNN** [comment]
@quadrupleslap: from looking at the documentation, yes it does! Thanks for the heads up 😄 

(That API did not exist when this issue was opened).
