### ISSUE TITLE
Record serialization

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang-nursery/log#356]
So, I'm currently [investigating the idea](https://users.rust-lang.org/t/any-real-time-safe-logger-around/32135/9) of writing a `Log` implementation that is real-time safe. Which means that its `log()` method cannot perform any operation that takes unbounded time, including memory allocation, lock-based synchronization, and blocking I/O.

The way I intend to do it is rather standard in the real-time community: write the `Record`s in a lock-free bounded MPSC queue which feeds a non-RT thread that does the actual logging. If a log arrives while the queue is full, drop it, and notify the logging thread that an overrun occured so that it can in turn notify the developer to decrease log complexity or increase log queue capacity.

As the `Record` format is full of stack borrows and non-Send, it must be serialized before it can be sent between threads. Currently, there doesn't seem to be any serialization support available for `Record`, and given that it has serialization-hostile members like `fmt::Arguments`, I expect that writing a serializer will be a little bit of work.

Note that we're not talking about serde-like general-purpose serialization here, but about [abomonation](https://crates.io/crates/abomonation)-like "just make it Send and 'static as quickly as you can" in-process serialization. That's faster, easier to implement, requires no heavy dependencies, and is sufficient for any use case that I can think of.

Are you interested in me doing that work inside of the `log` crate? I think it is the best place for this code to live in, since it will be easier for the serializer to evolve as the `Record` format changes (as with the ongoing integration of key-value storage). On the other hand, it will be a bit of maintenance burden for something that is ultimately a relatively niche use case, so I'll understand if you prefer me to keep the implementation on my side.

**Comment by sfackler** [comment]
Serialization of `fmt::Arguments` is just `args.to_string()`.

Generally speaking, we want to keep the log crate itself very small since it is ~univerally depended upon. Functionality that a logging implementation needs should generally live in that logging implementation (or a separate library if multiple implementations want to share it).

**Comment by HadrienG2** [comment]
> Serialization of `fmt::Arguments` is just `args.to_string()`.

Not in RT code ;) But yes, I would also go for lossy `Display`-based serialization.

> Generally speaking, we want to keep the log crate itself very small since it is ~univerally depended upon. Functionality that a logging implementation needs should generally live in that logging implementation (or a separate library if multiple implementations want to share it).

Thanks for the answer! I'll implement this on my logger's side, then.
