### ISSUE TITLE
failure to build with Rust 1.16.0

### ISSUE THREAD

**Issue by cardoe** [rust-lang-nursery/log#358]
```
$ git show
commit 70b78abf071a2849e20861df99bbd6b1e889ef71 (HEAD, tag: 0.4.8)
Merge: b0957ea 782d4f7
Author: Ashley Mannix <ashleymannix@live.com.au>
Date:   Mon Jul 29 07:03:20 2019 +1000

    Merge pull request #345 from KodrAus/cargo/0.4.8

    prepare for 0.4.8 release
$ cargo +1.16.0 build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling cfg-if v0.1.10
   Compiling log v0.4.8 (file:///Users/cardoe/work/log)
error: expected one of `,` or `=`, found `::`
   --> /Users/cardoe/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/src/lib.rs:143:19
    |
143 |     #[allow(clippy::assertions_on_constants)]
    |                   ^^

error: expected one of `=` or `]`, found `::`
   --> /Users/cardoe/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/src/lib.rs:143:19
    |
143 |     #[allow(clippy::assertions_on_constants)]
    |                   ^^

error: aborting due to previous error

error: Could not compile `cfg-if`.
Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by cardoe** [comment]
A bit confused by this but when I bisect `cfg-if` it shows that https://github.com/alexcrichton/cfg-if/commit/3e311415b29781b886a6b6611206305cec9527a7 breaks support with 1.16.0.

**Comment by cardoe** [comment]
However it seems more plausible that the break is caused by https://github.com/alexcrichton/cfg-if/commit/75e817fa2cdd9d3cb2c558fa91ba3dacdbfa8d73

**Comment by sfackler** [comment]
As you've noted, the error is caused by the cfg-if crate. If you need to build against 1.16, you can downgrade that package to a working version.

**Comment by cardoe** [comment]
@sfackler I think you closed this prematurely. https://github.com/alexcrichton/cfg-if is a dependency of this crate. I don't use Rust 1.16.0 but I am a maintainer of https://github.com/cardoe/stderrlog-rs which this crate advertises. Since this crate says it strictly supports Rust 1.16.0 and newer, I tests all commits against my crate with Rust 1.16.0. Unfortunately due to changes in https://github.com/alexcrichton/cfg-if there is no version of this crate that builds anymore which works with Rust 1.16.0.

How am I suppose to fix a dependency of `log`?

**Comment by cardoe** [comment]
The console output was me attempting to build this crate (`log`), @sfackler and it failing.

**Comment by sfackler** [comment]
`cargo update -p cfg-if --precise 0.1.9`
