### ISSUE TITLE
Add color support to env_logger

### ISSUE THREAD

**Issue by lfairy** [rust-lang-nursery/log#37]
On Unix, we can use the [`ansi_term`](http://bsago.me/doc/ansi_term/) crate or roll our own. I'm not sure how it works on Windows; we can just skip colors there for now.

As for configuration: we can add a new environment variable `RUST_LOG_COLOR`. It will take the values `never`, `always`, or `auto` (default). If `auto`, the logger will use color only when stderr is connected to a terminal.

**Comment by FredrikNoren** [comment]
:+1:

**Comment by calebmer** [comment]
Color support along the lines of `ansi_term` would be very nice.

**Comment by antoyo** [comment]
The [`pretty_env_logger` crate](https://crates.io/crates/pretty_env_logger) supports this.

**Comment by KodrAus** [comment]
We've got https://github.com/sebasmagri/env_logger/issues/2 in `env_logger`s new home to discuss this so I'll go ahead and close this one now.
