### ISSUE TITLE
#[macro_use(info)] raise error: macro undefined: 'log!'

### ISSUE THREAD

**Issue by Narann** [rust-lang-nursery/log#54]
Code:

``` rust
#[macro_use(info)]
extern crate log;
```

Error:

``` rust
<log macros>:4:1: 4:4 error: macro undefined: 'log!'
<log macros>:4 log ! ( $ crate:: LogLevel:: Info , $ ( $ arg ) * ) ; )
               ^~~
```

I will use `#[macro_use]` for now but I thought it was interesting [to limit](https://doc.rust-lang.org/stable/reference.html#macro-related-attributes) the macro to import in the namespace

``` bash
$rustc --version
rustc 1.1.0-dev
```

**Comment by Amanieu** [comment]
The `info`, `warn`, `error` and `trace` macros all use the `log` macro internally, so just specifying `#[macro_use(info, log)]` should work.

**Comment by dtolnay** [comment]
This is annoying. Is there a way this could be handled better using `$crate`? Have `info!` expand to an `#[inline(always)]` `#[doc(hidden)]` helper rather than to `log!`.

**Comment by sfackler** [comment]
`log!` needs to be a macro because it invokes `file!`, `module_path!` and `line!`. We could duplicate `log!`'s logic into `info!` etc which would avoid the import issue.

How many people actually selectively import log macros, though?

**Comment by seanmonstar** [comment]
Rust issue: https://github.com/rust-lang/rust/issues/25003

**Comment by mjkillough** [comment]
> `log!` needs to be a macro because it invokes `file!`, `module_path!` and `line!`. We could duplicate `log!`'s logic into `info!` etc which would avoid the import issue.

The bulk of the `log!` macro could be moved into an inlined helper function which is used by the `log!`/`error!`/`...` macros, with each passing the output of `file!`/`module_path!`/`line!` in as arguments to the function. There wouldn't be much duplication, but the helper function would have to be part of the public API of the `log` crate, which is a little ugly.

However, I'd be tempted to just duplicate `log!`'s logic into the other macros. There isn't that much to it.

**Comment by derekdreery** [comment]
This is going to come up with Rust 2018 - because you now import macros, the `info!` macro will fail unless you also import the `log!` macro.
