### ISSUE TITLE
should we use rust log instead?

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang-nursery/log#57]
I need the ability to use the debug!() logging macros with a separate logger implementation per thread.

I see the default rust liblog module has this feature - and after building a logger implementation built on spdlog with both modules I prefer the default rust liblog module.

However, the default rust liblog module is marked as unstable/private - and recommends this github log library.

Am I wasting my time with the liblog module provided with Rust?  (will it go away and be replaced by this github repo?) (which would be sad because I'm not seeing how to support per-thread loggers with this github log module)

Thanks!

**Comment by sfackler** [comment]
You should be able to write a logger implementation that allows configuration per-thread without too much trouble.

**Comment by MarkSwanson** [comment]
Thanks!

It's just that all the functionality I need is in the build-in liblog...
If this will be supported in the log run, I'd like to do that.

I guess I'm hoping someone is going to say, yeah - liblog is on track to be a stable supported module.

**Comment by sfackler** [comment]
I believe the old liblog used a thread local logger only due to historical baggage from the time before global state existed in Rust. The built in liblog will never be stabilized and only exists for use in rustc and rustdoc at this point. It may end up being replaced entirely by the new liblog + env_logger at some point if they are ever brought in-tree.

Here's a `Log` implementation that should do what you want (untested). You may want to handle the default case differently than this, which will ignore messages if they aren't installed.

```rust
thread_local!(static LOGGER: RefCell<Option<Box<Log>>> = None);

pub fn set_thread_logger(logger: Box<Log>) {
    LOGGER.with(|logger| {
        *logger.borrow_mut() = Some(logger);
    })
}

pub fn init() -> Result<(), SetLoggerError> {
    log::set_logger(|max_log_level| {
        max_log_level.set(LogLevelFilter::max());
        Box::new(ThreadLocalLogger)
    })
}

struct ThreadLocalLogger;

impl Log for ThreadLocalLogger {
    fn enabled(&self, metadata: &LogMetadata) -> bool {
        LOGGER.with(|logger| {
            match *logger.borrow() {
                Some(ref logger) => logger.enabled(metadata),
                None => false
            }
        });
    }

    fn log(&self, record: &LogRecord) {
        LOGGER.with(|logger| {
            match *logger.borrow_mut() {
                Some(ref mut logger) => logger.log(record),
                None => {}
            }
        });
    }
}
```

**Comment by MarkSwanson** [comment]
I created a logger proxy and logger based on your idea and it works great.

Thanks for responding so quickly with such a great idea!
