### ISSUE TITLE
Add ability to log (warnings) only once

### ISSUE THREAD

**Issue by Luthaf** [rust-lang-nursery/log#60]
Having a function which send a warning is nice to send message to the users about potential issues in the input. But when this function is called in an inner loop, the lot of identical `WARNING` messages can be annoying.

Would it be possible to add a `warn_once!` macro, which would only send the warning once? The `error_once!`, `info_once!`, `debug_once!` and `trace_once!` can also be added, for consistency.

**Comment by Luthaf** [comment]
For anyone interested, these macro can be implemented easily as:

```rust
#[macro_use]
extern crate log;

use std::sync::{Once, ONCE_INIT};
macro_rules! warn_once {
    ($($arg:tt)*) => ({
        static WARN_ONCE: Once = ONCE_INIT;
        WARN_ONCE.call_once(|| {
            warn!($($arg)*);
        });
    })
}
```

**Comment by Amanieu** [comment]
Here's a simple implementation:
```rust
macro_rules! warn_once {
    ($($args:tt)*) => {{
        static ONCE: ::std::sync::Once = ::std::sync::ONCE_INIT;
        ONCE.call_once(|| {
            warn!($($args)*);
        });
    }}
}
```

**Comment by Luthaf** [comment]
I thought of this implementation, but this do log only once, whatever the arguments of `warn!` are. I think logging once by combination of arguments would be the expected behaviour (or at least this is what I want).

Consider the following snippet:
```rust
fn foo() {
    for name in &["bar", "baz"] {
        warn_once!("Building the warning: {}", name);
    }
}
```

This should produce 2 warnings, no matter how many time the `foo` function is called.

**Comment by Amanieu** [comment]
This is much more complicated to implement, since you then need to keep track of all past log messages to see if this one has been printed before. I think you would be better off implementing such functionality in your own code rather than in the `log` crate.

**Comment by Luthaf** [comment]
> I think you would be better off implementing such functionality in your own code rather than in the log crate.

I still think this would be usefull for all the log users. But I think I'll try to implement that for myself at some point, and then propose a PR here. Last time I had a look, the solution I found needed to overwrite the `log!` macro, and thus the corresponding code must be in the log crate.

**Comment by Luthaf** [comment]
So I found a solution for that, storing the message inside a set and checking if the message was already stored or not. 

```rust
#[macro_use]
extern crate log;
#[macro_use]
extern crate lazy_static;

macro_rules! warn_once {
    ($($args:tt)*) => {{
        use ::std::collections::BTreeSet;
        use ::std::sync::Mutex;
        lazy_static!{
            static ref LAST_WARNINGS: Mutex<BTreeSet<String>> = Mutex::new(BTreeSet::new());
        }
        let mut warnings = LAST_WARNINGS.lock().expect("Mutex was poisonned");
        let message = format!($($args)*);
        let already_logged = warnings.contains(&message);
        if !already_logged {
            warnings.insert(message.clone());
            warn!("{}", message);
        }
    }};
}
```

This is fixed for me, but if you want me to submit this for inclusion in this crate I can do it.

**Comment by Luthaf** [comment]
I extracted this code and published it to [crates.io](https://crates.io/crates/log-once) as the `log-once` crate.

If you need this functionality, use the crate!
