### ISSUE TITLE
log + DynamicLibrary

### ISSUE THREAD

**Issue by 0x0G** [rust-lang-nursery/log#61]
Is it possible to use `DynamicLibrary::open(Some(&path))` and then execute it functions:

```rust
unsafe {
    std::mem::transmute(lib.symbol::<u8>("test_function").unwrap())
}
```

that use logger within?

In dyn lib:
```rust
#[no_mangle]
pub extern fn test_function() -> Result<()> {
    warn!("MESSAGE_FROM_DYN_LIB");
    Ok(())
}
```

In my case, the log messages from the dynamic library is not displayed.

**Comment by alexcrichton** [comment]
The dynamic library will have its own copy of the logging backend (e.g. `env_logger`) which also needs to be initialized, but once that happens it should work just fine!

**Comment by sfackler** [comment]
If the plugin and main program both dynamically link the log crate, they should be able to share a logger as well.
