### ISSUE TITLE
env: Allow zero-allocation LogBuilder::format?

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang-nursery/log#72]
The the "format function" passed to LogBuilder::format must implement `Fn(&LogBuilder) -> String`.  That is, it must allocate a new string on the heap for every message logged. The string is discarded immediately after env_logger::Logger writes to stderr.

Would you consider, instead, making the signature `Fn(&LogBuilder, &mut std::io::Write) -> io::Result`?  That way, customized env loggers could write directly to stderr without creating a String.

**Comment by KodrAus** [comment]
Thanks for the suggestion @tomjakubowski! We did end up doing this in https://github.com/sebasmagri/env_logger/pull/19
