### ISSUE TITLE
Use of logging prevents (threaded) SDL application from exiting

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang-nursery/log#74]
I've only tested this on Windows, and I don't have a small reproduction I can share. I'll edit this issue once I have more information.

This might be caused from the combination of rust-sdl2 and logging, or the use of threads, or the combination of both. But as soon as I started to use the `log` crate (along with `env_logger`), whenever my application tries to exit, it seems to get stuck in an infinite loop. The SDL window closes, the end of `main` is reached, but the program doesn't exit.

**Comment by alexcrichton** [comment]
Could you use gdb/lldb/visual studio to get some kind of a backtrace? That'd probably help figuring out the culprit here. This sounds pretty unrelated to the `log` crate itself, but you never know!

**Comment by sfackler** [comment]
This crate does register an atexit handler that will loop, but only while things are actively logging. If threads are getting hard-killed, you could end up in a situation where one of them was in the middle of logging when that happened so the atexit handler will loop forever. We should probably add a bail-out point there.

**Comment by jonas-schievink** [comment]
The loop in the handler is not the problem - I replaced the loop body with a panic, it's never hit. I also can't reproduce using wine, or natively running on Linux.

I have also noticed that debugging using gdb on Windows is such an absolute nightmare it's not even funny, so no backtrace or anything (gdbserver also doesn't work for some reason, so I can't even *attempt* to do it remotely - "Remote register badly formatted"). Looks like I'll have to install *an entire IDE* to make it work.

I'm not entirely sure that this is really just an issue with the log crate, I suspect (without a real reason) some interaction with SDL.

I'll install VS and try to reduce my crate to something manageable. Sorry for the messy bug report and thanks for your patience :)

**Comment by jonas-schievink** [comment]
...and as always, I'm wrong. SDL is innocent and the loop *is* the culprit (panicking in an atexit handler seems to produce no output, because *who the hell would do that*), removing it makes the program exit normally every time.

Reasonably small reproduction (hyper does some logging internally AFAIK, so it might just be an innocent bystander when this happened): https://gist.github.com/jonas-schievink/d61822195d12a7c8ee9b

**Comment by alexcrichton** [comment]
Ah yeah that may do it, part of returning from main may terminate other threads and then run atexit handlers perhaps?

**Comment by sfackler** [comment]
This is pretty unfortunate. I'm kind of tempted to remove the atexit logic altogether at that point if we can't make it work reliably.
