### ISSUE TITLE
Provide benchmarks for env-logger

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/log#75]
From the README and the docs, I didn't see anything about how fast the log / don't log decision is. In particular, I'm interested in whether using env-controled `debug!` in performance-sensitive code would be a good idea or not.

**Comment by sfackler** [comment]
The environment variable is parsed once when the logger is installed. Each log call involves a linear scan of all logging directives: https://github.com/rust-lang-nursery/log/blob/master/env/src/lib.rs#L287, so I'd expect the performance would be pretty reasonable unless you have a very complex value of `RUST_LOG`.

This could obviously be optimized if it ends up insufficiently performant in practice.

**Comment by kamalmarhubi** [comment]
That's good to know. I still like the idea of having some benchmarks with a few different numbers of directives. It'd also be interesting to know what env-logger adds compared to plain log when `RUST_LOG` is empty.

I can eventually get around to it myself, just wanted to register interest via an issue.

**Comment by sfackler** [comment]
Yep, definitely seems like a reasonable thing to have.

**Comment by sfackler** [comment]
env_logger has moved out of tree.
