### ISSUE TITLE
Change environment variable name.

### ISSUE THREAD

**Issue by quadrupleslap** [rust-lang-nursery/log#83]
For `env_logger`, maybe keep the default as `RUST_LOG` and allow the users to change it as a config option? For example, I might want people to use MC_LOG to change the log level of my Minecraft clone.

**Comment by xetra11** [comment]
Yea that would be nice!
Because I want people who use my library use a library specific env variable to active the logging like "RR_LOG"

**Comment by dtolnay** [comment]
The workaround for now is:

```rust
let mut lb = env_logger::LogBuilder::new();
if let Ok(log_config) = env::var("MC_LOG") {
    lb.parse(&log_config);
}
lb.init()
```

**Comment by sfackler** [comment]
env_logger has moved out of tree.
