### ISSUE TITLE
'macro undefined' when adding log 0.3.6 to an executable

### ISSUE THREAD

**Issue by iamdanfox** [rust-lang-nursery/log#84]
I wanted to add logging to [my hello-world application][1], so I followed the instructions in the [README](https://github.com/rust-lang-nursery/log/tree/c679ad4f2cd8124ff5817c64c25ff1d35f96ddc3#in-executables), but I get the following error:

```
/Users/danfox/rust-hello-world/target/debug/build/rust-hello-world-35e574f972a5f97c/out/main.rs:235:5: 235:8 error: macro undefined: 'log!'
/Users/danfox/rust-hello-world/target/debug/build/rust-hello-world-35e574f972a5f97c/out/main.rs:235     log!("Starting server on localhost:3000");
                                                                                                        ^~~
error: aborting due to previous error
error: Could not compile `rust-hello-world`.
```

(This red build is [reproducible on travis][2])

[2]: https://travis-ci.org/iamdanfox/rust-hello-world/builds/133960256

Is the `log` crate known to be incompatible with syntex or am I just making a much simpler mistake?  Any suggestions on what to try next are welcome :)

[1]: https://github.com/iamdanfox/rust-hello-world/pull/1/files#diff-ad2c34e6fefa0304e1dbf2da6977541cR33

**Comment by sfackler** [comment]
It seems like it should work - can you look at the generated main file at `/Users/danfox/rust-hello-world/target/debug/build/rust-hello-world-35e574f972a5f97c/out/main.rs` and see if the `#[macro_use]` above the `extern crate log` is still present?

**Comment by iamdanfox** [comment]
@sfackler Yep, the generated `main.rs` starts with the following lines:

```rust
#[macro_use]
extern crate log;
extern crate env_logger;

extern crate iron;
extern crate bodyparser;

use iron::prelude::*;
use iron::status;

#[derive(Clone, Debug)]
struct Point {
    x: i32,
    y: i32,
}
#[allow(non_upper_case_globals, unused_attributes, unused_qualifications)]
const _IMPL_DESERIALIZE_FOR_Point: () =
    {
        extern crate serde as _serde;
// ... etc etc
```

**Comment by sfackler** [comment]
Ah, it's because the extern crate declaration is inside of a file that's `include!`d - if you move it out to the real main.rs along side the serde crates things work properly.

**Comment by iamdanfox** [comment]
Fantastic, that's worked perfectly: https://travis-ci.org/iamdanfox/rust-hello-world/builds/133967155

Do you think this might be worth documenting on the `serde` side?  I hadn't ever encountered `include!` before!

**Comment by sfackler** [comment]
Might be, yeah
