### ISSUE TITLE
Add ability to log to both env_logger and a custom logger

### ISSUE THREAD

**Issue by asajeffrey** [rust-lang-nursery/log#85]
At the moment, `env_logger::init` initializes the env logger, and registers it using the one-shot `log::set_logger`. This means there's no way to combine env logging with a custom logger.

Discussion on IRC with @alexcrichton here: http://logs.glob.uno/?c=mozilla%23servo&s=21+Jun+2016&e=21+Jun+2016#c459280

**Comment by hezhaozhao-git** [comment]
@asajeffrey I encountered the same problem, how should I deal with it? I have a channel sender that needs to send log, and at the same time I want the original log behavior. How should I do it?

**Comment by Thomasdezeeuw** [comment]
> @asajeffrey I encountered the same problem, how should I deal with it? I have a channel sender that needs to send log, and at the same time I want the original log behavior. How should I do it?

You can implement your own custom logger that calls zero or more others loggers.
