### ISSUE TITLE
docs: add example of initializing the logger from a unit test

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang-nursery/log#87]
Since I do not expect https://github.com/rust-lang/rfcs/issues/1664 to be addressed in the short term, it would be a good idea to update the docs for `env_logger` to include an example usage on a few `#[test]` functions in addition to the current `fn main`.

(That is, I think the current docs leave a lot up to the intutition of the reader in terms of understanding how to generalize that one use of `env_logger` to other contexts.)

**Comment by dtolnay** [comment]
Looks like this was added to the readme in #56. It still needs to be added to `env_logger`'s documentation.

**Comment by sfackler** [comment]
env_logger has moved out of tree.
